@Minimal.Api_HostAddress = https://localhost:7046

POST {{Minimal.Api_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":false
}

###

@id=1
PUT {{Minimal.Api_HostAddress}}/todoitems/{{id}}
Content-Type: application/json

{
  "id": 1,
  "name": "feed fish",
  "isComplete": false
}

###



